<img src="../../../images/banners/data_processing.png" width="600"/>

# <img src="../../../images/logos/python.png" width="23"/> Indexing and Filter (Problems)


**Question:**  
How many kinds of indexing there are in NumPy?

**Answer:**  
There are different kinds of indexing available depending on obj:
- Basic indexing
- Advanced indexing
- Field access

---

**Question:**  
What's the different between indexing and slicing in NumPy?

**Answer:**  
`Indexing` refers to the process of accessing a **single element or a group of elements** in an array by specifying their index or indices. In NumPy, indexing an array is done using square brackets `[]`.

`Slicing` refers to the process of accessing **a subset of elements** in an array by specifying a range of indices. Slicing is done using the colon `:` operator inside the square brackets `[]`. 

For example:
```
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr[0, 1]  # indexing: access element at row 0, column 1
subset = arr[:2, :2]  # slicing: slice first two rows and first two columns
```

---

**Question:**  
NumPy basic slicing creates a view or a copy of the array?

**Answer:**  
NumPy basic slicing creates a view instead of a copy as in the case of built-in Python sequences such as string, tuple and list. Care must be taken when extracting a small portion from a large array which becomes useless after the extraction, because the small portion extracted contains a reference to the large original array whose memory will not be released until all arrays derived from it are garbage-collected. In such cases an explicit copy() is recommended.

---

**Question:**
What is the difference between `x[2]` and `x[0:2]` in the code below?
```
import numpy as np
x = np.array([
    [2, 0, 8, 4],
    [9, 4, 6, 8],
    [1, 3, 4, 6],
])
print(x[2])
print(x[0:2])
```
**Answer:**  
The output of `x[2]` (indexing) is the entire row with index 2 of array `x` that is equal to:
```
[1 3 4 6]
```
The output of `x[0:2]` (slicing) is a array with shape (2, 4) contains two rows of array `x` with index 0 and 1 that is equal to:
```
[[2 0 8 4]
 [9 4 6 8]]
```

---

**Question:**  
What's NumPy advanced indexing?

**Answer:**  
Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view) and there are two types of advanced indexing in NumPy:
- **Integer array indexing**: This type of indexing is used when you want to access a specific set of elements in an array by specifying an array of indices. The indices can be provided as a single array, or as multiple arrays with the same shape.

- **Boolean array indexing**: This type of indexing is used when you want to select elements in an array based on a Boolean mask. The mask is an array of the same shape as the original array, where each element is either True or False. When you index an array with a Boolean mask, the resulting array contains only the elements where the corresponding value in the mask is True. 

For example:
```
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

indices1 = np.array([0, 2])
indices2 = np.array([1, 2])
subset = arr[indices1, indices2]  # select elements at (0,1) and (2,2)
mask = arr > 5
subset = arr[mask]  # select elements greater than 5
```

---

**Question:**  
We have an array like below. What is the difference between `x[0, 2]` and `x[[0, 2]]`?
```
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])
```
**Answer:**  
`x[0, 2]` is bacic indexing and the output is 30  
`x[[0, 2]]` is advanced indexing and returns a copy of row 0 and row 2 of array x:
```
[[10 20 30]
 [70 80 90]]
 ```

---

**Question:**  
Can You use `and`, `or` operators in advanced indexing?

**Answer:**  
No, because the `and` , `or`  operate on the truth value of the whole array, not element by element.  
You have to use `binary` operators such as `&`, `|`, `~` and etc.  NumPy designates them as the vectorized, element-wise operators to combine Booleans.


---

**Question:**  
Consider the following array. Calculate the `sum` of elements greater than 20 and less than 90.
```
x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])
```
**Answer:**  
```
x[(x > 20) & (x < 90)].sum()
```
result = 330

---