<img src="../../../images/banners/data_processing.png" width="600"/>

# <img src="../../../images/logos/python.png" width="23"/>Order and Aggregate (Problems)

**Question:**  
What is the default axis in `np.sort()` and what is the difference between this function and `.sort()` method?

**Answer:**  
The default axis is `-1` which means the last axis (the innermost dimension). The difference is `np.sort()` function returns a copy sorted array but `.sort()` method sorts the array in-place.


---

**Question:**   
Consider following array. Explain what's the difference between`np.sort(x, axis=0)` and `np.sort(x, axis=1)`?
```
x = np.array([
    [20, 70, 60],
    [80, 50, 30],
    [40, 10, 90],
])
```
**Answer:**  
In output of `np.sort(x, axis=0)`, each column of the array still has all of its elements but they have been sorted low-to-high inside that column:
```
[[20 10 30]
 [40 50 60]
 [80 70 90]]
```
Similarly `np.sort(x, axis=1)` do the same for rows:
```
[[20 60 70]
 [30 50 80]
 [10 40 90]]
```


---

**Question:**  
What's the use of `concatenate()` function in NumPy?

**Answer:**  
The `concatenate()` function in NumPy is used to join two or more arrays along a **specified axis**. It takes a sequence of arrays as input and returns a new array that contains the concatenated elements of the input arrays.

The arrays must have the same shape, **except** in the dimension corresponding to `axis`.

Note that if `axis=None` then the input arrays are flattened before concatenation. 

---

**Question:**  
What's the difference the `hstack()` and `vstack()` functions in NumPy?

**Answer:**  
The main difference is the axis along which the arrays are stacked. `hstack()` stacks arrays horizontally along the second axis, while `vstack()` stacks arrays vertically along the first axis.

---

**Question:**  
What are the aggregating functions in NumPy? Give some examples.

**Answer:**  
These functions are used to perform operations on arrays that aggregate the elements along one or more axes, resulting in a single value or a smaller array.

Here are some of the aggregating functions in NumPy:

- `np.sum()`
- `np.mean()`
- `np.min()`
- `np.max()`
- `np.prod()`
- `np.std()`
- `np.var()`
- `np.any()`
- `np.all()`
- `np.argmin()`
- `np.argmax()`
- `np.median()`
- `np.percentile()`
- `np.quantile()`

---